spring:
    application:
        name: organization
    datasource:
        url: jdbc:h2:mem:organization
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
